// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.6
// source: statistics.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Statistics_CrawlerChanged_FullMethodName = "/api.Statistics/CrawlerChanged"
	Statistics_SpiderChanged_FullMethodName  = "/api.Statistics/SpiderChanged"
	Statistics_JobChanged_FullMethodName     = "/api.Statistics/JobChanged"
	Statistics_TaskChanged_FullMethodName    = "/api.Statistics/TaskChanged"
	Statistics_RequestChanged_FullMethodName = "/api.Statistics/RequestChanged"
	Statistics_ItemChanged_FullMethodName    = "/api.Statistics/ItemChanged"
	Statistics_GetCrawlers_FullMethodName    = "/api.Statistics/GetCrawlers"
	Statistics_GetSpiders_FullMethodName     = "/api.Statistics/GetSpiders"
	Statistics_GetJobs_FullMethodName        = "/api.Statistics/GetJobs"
	Statistics_GetTasks_FullMethodName       = "/api.Statistics/GetTasks"
	Statistics_GetRequests_FullMethodName    = "/api.Statistics/GetRequests"
	Statistics_GetItems_FullMethodName       = "/api.Statistics/GetItems"
)

// StatisticsClient is the client API for Statistics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatisticsClient interface {
	CrawlerChanged(ctx context.Context, in *Crawler, opts ...grpc.CallOption) (*Response, error)
	SpiderChanged(ctx context.Context, in *Spider, opts ...grpc.CallOption) (*Response, error)
	JobChanged(ctx context.Context, in *Job, opts ...grpc.CallOption) (*Response, error)
	TaskChanged(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Response, error)
	RequestChanged(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	ItemChanged(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Response, error)
	GetCrawlers(ctx context.Context, in *RequestCrawlers, opts ...grpc.CallOption) (*ResponseCrawlers, error)
	GetSpiders(ctx context.Context, in *RequestSpiders, opts ...grpc.CallOption) (*ResponseSpiders, error)
	GetJobs(ctx context.Context, in *RequestJobs, opts ...grpc.CallOption) (*ResponseJobs, error)
	GetTasks(ctx context.Context, in *RequestTasks, opts ...grpc.CallOption) (*ResponseTasks, error)
	GetRequests(ctx context.Context, in *RequestRequests, opts ...grpc.CallOption) (*ResponseRequests, error)
	GetItems(ctx context.Context, in *RequestItems, opts ...grpc.CallOption) (*ResponseItems, error)
}

type statisticsClient struct {
	cc grpc.ClientConnInterface
}

func NewStatisticsClient(cc grpc.ClientConnInterface) StatisticsClient {
	return &statisticsClient{cc}
}

func (c *statisticsClient) CrawlerChanged(ctx context.Context, in *Crawler, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Statistics_CrawlerChanged_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsClient) SpiderChanged(ctx context.Context, in *Spider, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Statistics_SpiderChanged_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsClient) JobChanged(ctx context.Context, in *Job, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Statistics_JobChanged_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsClient) TaskChanged(ctx context.Context, in *Task, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Statistics_TaskChanged_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsClient) RequestChanged(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Statistics_RequestChanged_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsClient) ItemChanged(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Statistics_ItemChanged_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsClient) GetCrawlers(ctx context.Context, in *RequestCrawlers, opts ...grpc.CallOption) (*ResponseCrawlers, error) {
	out := new(ResponseCrawlers)
	err := c.cc.Invoke(ctx, Statistics_GetCrawlers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsClient) GetSpiders(ctx context.Context, in *RequestSpiders, opts ...grpc.CallOption) (*ResponseSpiders, error) {
	out := new(ResponseSpiders)
	err := c.cc.Invoke(ctx, Statistics_GetSpiders_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsClient) GetJobs(ctx context.Context, in *RequestJobs, opts ...grpc.CallOption) (*ResponseJobs, error) {
	out := new(ResponseJobs)
	err := c.cc.Invoke(ctx, Statistics_GetJobs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsClient) GetTasks(ctx context.Context, in *RequestTasks, opts ...grpc.CallOption) (*ResponseTasks, error) {
	out := new(ResponseTasks)
	err := c.cc.Invoke(ctx, Statistics_GetTasks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsClient) GetRequests(ctx context.Context, in *RequestRequests, opts ...grpc.CallOption) (*ResponseRequests, error) {
	out := new(ResponseRequests)
	err := c.cc.Invoke(ctx, Statistics_GetRequests_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsClient) GetItems(ctx context.Context, in *RequestItems, opts ...grpc.CallOption) (*ResponseItems, error) {
	out := new(ResponseItems)
	err := c.cc.Invoke(ctx, Statistics_GetItems_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatisticsServer is the server API for Statistics service.
// All implementations must embed UnimplementedStatisticsServer
// for forward compatibility
type StatisticsServer interface {
	CrawlerChanged(context.Context, *Crawler) (*Response, error)
	SpiderChanged(context.Context, *Spider) (*Response, error)
	JobChanged(context.Context, *Job) (*Response, error)
	TaskChanged(context.Context, *Task) (*Response, error)
	RequestChanged(context.Context, *Request) (*Response, error)
	ItemChanged(context.Context, *Item) (*Response, error)
	GetCrawlers(context.Context, *RequestCrawlers) (*ResponseCrawlers, error)
	GetSpiders(context.Context, *RequestSpiders) (*ResponseSpiders, error)
	GetJobs(context.Context, *RequestJobs) (*ResponseJobs, error)
	GetTasks(context.Context, *RequestTasks) (*ResponseTasks, error)
	GetRequests(context.Context, *RequestRequests) (*ResponseRequests, error)
	GetItems(context.Context, *RequestItems) (*ResponseItems, error)
	mustEmbedUnimplementedStatisticsServer()
}

// UnimplementedStatisticsServer must be embedded to have forward compatible implementations.
type UnimplementedStatisticsServer struct {
}

func (UnimplementedStatisticsServer) CrawlerChanged(context.Context, *Crawler) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrawlerChanged not implemented")
}
func (UnimplementedStatisticsServer) SpiderChanged(context.Context, *Spider) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpiderChanged not implemented")
}
func (UnimplementedStatisticsServer) JobChanged(context.Context, *Job) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JobChanged not implemented")
}
func (UnimplementedStatisticsServer) TaskChanged(context.Context, *Task) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskChanged not implemented")
}
func (UnimplementedStatisticsServer) RequestChanged(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestChanged not implemented")
}
func (UnimplementedStatisticsServer) ItemChanged(context.Context, *Item) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ItemChanged not implemented")
}
func (UnimplementedStatisticsServer) GetCrawlers(context.Context, *RequestCrawlers) (*ResponseCrawlers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCrawlers not implemented")
}
func (UnimplementedStatisticsServer) GetSpiders(context.Context, *RequestSpiders) (*ResponseSpiders, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSpiders not implemented")
}
func (UnimplementedStatisticsServer) GetJobs(context.Context, *RequestJobs) (*ResponseJobs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobs not implemented")
}
func (UnimplementedStatisticsServer) GetTasks(context.Context, *RequestTasks) (*ResponseTasks, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTasks not implemented")
}
func (UnimplementedStatisticsServer) GetRequests(context.Context, *RequestRequests) (*ResponseRequests, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRequests not implemented")
}
func (UnimplementedStatisticsServer) GetItems(context.Context, *RequestItems) (*ResponseItems, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItems not implemented")
}
func (UnimplementedStatisticsServer) mustEmbedUnimplementedStatisticsServer() {}

// UnsafeStatisticsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatisticsServer will
// result in compilation errors.
type UnsafeStatisticsServer interface {
	mustEmbedUnimplementedStatisticsServer()
}

func RegisterStatisticsServer(s grpc.ServiceRegistrar, srv StatisticsServer) {
	s.RegisterService(&Statistics_ServiceDesc, srv)
}

func _Statistics_CrawlerChanged_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Crawler)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServer).CrawlerChanged(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Statistics_CrawlerChanged_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServer).CrawlerChanged(ctx, req.(*Crawler))
	}
	return interceptor(ctx, in, info, handler)
}

func _Statistics_SpiderChanged_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Spider)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServer).SpiderChanged(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Statistics_SpiderChanged_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServer).SpiderChanged(ctx, req.(*Spider))
	}
	return interceptor(ctx, in, info, handler)
}

func _Statistics_JobChanged_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Job)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServer).JobChanged(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Statistics_JobChanged_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServer).JobChanged(ctx, req.(*Job))
	}
	return interceptor(ctx, in, info, handler)
}

func _Statistics_TaskChanged_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServer).TaskChanged(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Statistics_TaskChanged_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServer).TaskChanged(ctx, req.(*Task))
	}
	return interceptor(ctx, in, info, handler)
}

func _Statistics_RequestChanged_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServer).RequestChanged(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Statistics_RequestChanged_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServer).RequestChanged(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Statistics_ItemChanged_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Item)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServer).ItemChanged(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Statistics_ItemChanged_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServer).ItemChanged(ctx, req.(*Item))
	}
	return interceptor(ctx, in, info, handler)
}

func _Statistics_GetCrawlers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCrawlers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServer).GetCrawlers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Statistics_GetCrawlers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServer).GetCrawlers(ctx, req.(*RequestCrawlers))
	}
	return interceptor(ctx, in, info, handler)
}

func _Statistics_GetSpiders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestSpiders)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServer).GetSpiders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Statistics_GetSpiders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServer).GetSpiders(ctx, req.(*RequestSpiders))
	}
	return interceptor(ctx, in, info, handler)
}

func _Statistics_GetJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestJobs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServer).GetJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Statistics_GetJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServer).GetJobs(ctx, req.(*RequestJobs))
	}
	return interceptor(ctx, in, info, handler)
}

func _Statistics_GetTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestTasks)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServer).GetTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Statistics_GetTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServer).GetTasks(ctx, req.(*RequestTasks))
	}
	return interceptor(ctx, in, info, handler)
}

func _Statistics_GetRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestRequests)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServer).GetRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Statistics_GetRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServer).GetRequests(ctx, req.(*RequestRequests))
	}
	return interceptor(ctx, in, info, handler)
}

func _Statistics_GetItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestItems)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServer).GetItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Statistics_GetItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServer).GetItems(ctx, req.(*RequestItems))
	}
	return interceptor(ctx, in, info, handler)
}

// Statistics_ServiceDesc is the grpc.ServiceDesc for Statistics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Statistics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Statistics",
	HandlerType: (*StatisticsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CrawlerChanged",
			Handler:    _Statistics_CrawlerChanged_Handler,
		},
		{
			MethodName: "SpiderChanged",
			Handler:    _Statistics_SpiderChanged_Handler,
		},
		{
			MethodName: "JobChanged",
			Handler:    _Statistics_JobChanged_Handler,
		},
		{
			MethodName: "TaskChanged",
			Handler:    _Statistics_TaskChanged_Handler,
		},
		{
			MethodName: "RequestChanged",
			Handler:    _Statistics_RequestChanged_Handler,
		},
		{
			MethodName: "ItemChanged",
			Handler:    _Statistics_ItemChanged_Handler,
		},
		{
			MethodName: "GetCrawlers",
			Handler:    _Statistics_GetCrawlers_Handler,
		},
		{
			MethodName: "GetSpiders",
			Handler:    _Statistics_GetSpiders_Handler,
		},
		{
			MethodName: "GetJobs",
			Handler:    _Statistics_GetJobs_Handler,
		},
		{
			MethodName: "GetTasks",
			Handler:    _Statistics_GetTasks_Handler,
		},
		{
			MethodName: "GetRequests",
			Handler:    _Statistics_GetRequests_Handler,
		},
		{
			MethodName: "GetItems",
			Handler:    _Statistics_GetItems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "statistics.proto",
}
